import initTabNavigation from "./modules/tabNavigate.js";
import initScrollAnimation from "./modules/scrollAnimation.js";
import initScrollSuave from "./modules/scrollSuave.js";
import initAccordionList from "./modules/accordionList.js";
import initModal from "./modules/modal.js";
import initTooltip from "./modules/tooltip.js";
import initDropDownMenu from "./modules/dropMenu.js";
import initMenuMobile from "./modules/menuMobile.js";
import initFetchAnimais from "./modules/fetchAnimais.js";
import initFetchBitcoin from "./modules/fetchBitcoin.js";

initScrollSuave();
initScrollAnimation();
initTabNavigation();
initAccordionList();
initModal();
initTooltip();
initDropDownMenu();
initMenuMobile();
initFetchAnimais();
initFetchBitcoin();